on:
  push:
    branches:
      - main

permissions: read-all

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # version 1.11.6
        with:
          app-id: ${{ vars.BN_RELEASER_APP_ID }}
          private-key: ${{ secrets.BN_RELEASER_PRIVATE_KEY }}
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # version 4.2.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          release-type: simple
